name: wafir_mobile
description: A new Flutter project for Wafir.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  flutter_riverpod: ^2.4.9
  riverpod_annotation: ^2.3.3
  go_router: ^13.0.0
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  fl_chart: ^0.66.0
  google_fonts: ^6.1.0
  fpdart: ^1.1.0
  json_annotation: ^4.8.1
  sqflite: ^2.3.0
  path: ^1.8.3
  connectivity_plus: ^5.0.2
  path_provider: ^2.1.5
  share_plus: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.9
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true
  generate: true
